name: Not Manually triggered workflow
on:
  push

jobs:
  say_hello:
    if: ${{ github.event_name == 'SOMETHING FALSE' }}
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Hello ${{ github.event.inputs.name }}!"
        echo "- in ${{ github.event.inputs.home }}!"

  job_2:
    runs-on: ubuntu-latest
    needs: [say_hello]
    if: ${{ always() }}
    steps:
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump needs context
        env:
          NEEDS_CONTEXT: ${{ toJson(needs) }}
        run: echo "$NEEDS_CONTEXT"
