name: Manually triggered workflow
on:
  workflow_dispatch:

jobs:
  example-job:
    runs-on: ubuntu-linux
    steps:
      - name: Retrieve secret
        env:
          super_secret: ${{ secrets.SUPERSECRET }}
        run: |
          echo "$SUPER_SECRET"
          echo ${#SUPER_SECRET}
