name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - uses: nohomers/composite-runs-action@master
        id: hello
        with:
          person_to_greet: "mona the octocat"
      - run: echo "was the greeting successful? -- ${{ steps.hello.outputs.greet_result }}"
