name: Greeting workflow
on:
  - push
  - pull_request
  - workflow_dispatch
jobs:
  build:
    # Job name is Greeting
    name: Greeting
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: Step1
        run: |
          echo "hi, there is no variable set."
          echo "var1=apples" >> $GITHUB_ENV
      # This step prints an output (time) from the previous step's action.
      - name: step 2
        if: env.var1 == "apples"
        run: echo "Is it still bananas? var1 is $var1"
