name: Greeting workflow
on:
  - push
  - pull_request
  - workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this will error" && exit 1
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo "this won't run"
  job3:
    runs-on: ubuntu-latest
    if: always()
    needs: [job1, job2]
    steps:
      - run: echo "this should always run" 
