name: Greeting workflow
on:
  - push
  - pull_request
  - workflow_dispatch
jobs:
  weekday_job:
    runs-on: windows-latest
    env:
      DAY_OF_WEEK: Mon
    steps:
      - name: "Hello world when it's Monday"
        if: env.DAY_OF_WEEK == 'Mon'
        run: echo "Hello world $FIRST_NAME $middle_name $Last_Name, sounds like you have a case of the Mondays!"
        env:
          FIRST_NAME: Mona
          middle_name: The
          Last_Name: Octocat
